# **Exploring Pandas - Part 2**

# **Module 3: Data Selection & Filtering**
* 1) Boolean Indexing & Filtering
* 2) Multiple Conditions (&, |, ~)
* 3) isin(), between()
* 4) query() Method
* 5) Filtering with loc[] (label-based)

In [ ]:
import pandas as pd

data = {
    'studentId': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Srinivas', 'Vas', 'Hello', 'Srinivas', 'OK', 'Hai', 'Hello', 'Vas'],
    'Age': [25, 30, 35, 40, 45, 30, 35, 28],
    'Course': ['ML', 'ML', 'ML', 'Python', 'DL', 'ML', 'DL', 'ML'],
    'City': ['Bangalore', 'Chennai', 'Bangalore', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'],
    'Fee': [20000, 25000, 15000, 18000, 22000, 21000, 17000, 24000]
}

mydf = pd.DataFrame(data)

mydf

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
1        102       Vas   30      ML    Chennai  25000
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
5        106       Hai   30      ML  Hyderabad  21000
6        107     Hello   35      DL       Pune  17000
7        108       Vas   28      ML    Chennai  24000

## **1) Boolean Indexing & Filtering**

In [ ]:
# Q1) What is the Boolean mask for students whose age is greater than 30?

mydf['Age'] > 30

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7    False
Name: Age, dtype: bool

In [ ]:
# Q2) Get all students whose age is greater than 30.

mydf[mydf['Age'] > 30]

   studentId      Name  Age  Course       City    Fee
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
6        107     Hello   35      DL       Pune  17000

In [ ]:
# Q3) Get all students who paid a fee of ₹20,000 or more.

mydf[mydf['Fee'] >= 20000]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
4        105        OK   45     DL      Delhi  22000
5        106       Hai   30     ML  Hyderabad  21000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q4) Get all students from Bangalore.

mydf[mydf['City'] == "Bangalore"]

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000

In [ ]:
# Q5) Get all students enrolled in the ML course.

mydf[mydf['Course'] == "ML"]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
2        103     Hello   35     ML  Bangalore  15000
5        106       Hai   30     ML  Hyderabad  21000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q5A) Get students Sid, Name and Course who enrolled in the ML course.

#a) All rows and All cols
print(mydf)
print("-"*50)

#b) Filtered rows and All cols
print(mydf[mydf['Course'] == "ML"])
print("-"*50)

#c) All rows and Filtered cols
print(mydf[["studentId","Name","Course"]])
print("-"*50)

#d) Filtered rows and Filtered cols
#mydf[mydf['Course'] == "ML"][["studentId","Name","Course"]]
mydf[["studentId","Name","Course"]][mydf['Course'] == "ML"]

## **2) Multiple Conditions (&, |, ~)**

In [ ]:
# Q6) Get all students whose age is greater than 30 and course is "ML".

mydf[(mydf['Age'] < 35) & (mydf['Course'] == "ML")]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
5        106       Hai   30     ML  Hyderabad  21000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q7) Get all students whose city is "Chennai" or "Bangalore".

mydf[(mydf['City'] == "Chennai") | (mydf['City'] == "Bangalore")]

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
1        102       Vas   30      ML    Chennai  25000
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
7        108       Vas   28      ML    Chennai  24000

In [ ]:
# Q8) Get all students not from "Bangalore".

mydf[~(mydf['City'] == "Bangalore")]

   studentId   Name  Age Course       City    Fee
1        102    Vas   30     ML    Chennai  25000
4        105     OK   45     DL      Delhi  22000
5        106    Hai   30     ML  Hyderabad  21000
6        107  Hello   35     DL       Pune  17000
7        108    Vas   28     ML    Chennai  24000

In [ ]:
# Q9) Get all students whose age is greater than 30 and fee is less than ₹20,000.

mydf[(mydf['Age'] > 30) & (mydf['Fee'] < 20000)]

   studentId      Name  Age  Course       City    Fee
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
6        107     Hello   35      DL       Pune  17000

In [ ]:
# Q10) Get all students whose course is not "Python" and fee is more than ₹20,000.

mydf[(mydf['Course'] != "Python") & (mydf['Fee'] > 20000)]

   studentId Name  Age Course       City    Fee
1        102  Vas   30     ML    Chennai  25000
4        105   OK   45     DL      Delhi  22000
5        106  Hai   30     ML  Hyderabad  21000
7        108  Vas   28     ML    Chennai  24000

In [ ]:
# Q11) Get all students whose Age > 25, Course is 'ML', and City is 'Bangalore'.

mydf[
    (mydf["Age"] >= 25) &
    (mydf["Course"] == "ML") &
    (mydf["City"] == "Bangalore")
]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
2        103     Hello   35     ML  Bangalore  15000

In [ ]:
# Q12) Get all students whose age >= 25, course is "ML", city is "Hyderabad", and name starts with "S".

mydf[
    (mydf["Age"] >= 25) &
    (mydf["Course"] == "ML") &
    (mydf["City"] == "Bangalore") &
    (mydf["Name"].str.startswith("S"))
]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000

## **3) isin(), between()**

In [ ]:
# Q13) Get all students whose city is "Chennai" or "Bangalore" or "Hyderabad" or "Delhi".

mydf[
     (mydf["City"] == "Chennai") |
     (mydf["City"] == "Bangalore") |
     (mydf["City"] == "Hyderabad") |
     (mydf["City"] == "Delhi")
    ]

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
1        102       Vas   30      ML    Chennai  25000
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
5        106       Hai   30      ML  Hyderabad  21000
7        108       Vas   28      ML    Chennai  24000

In [ ]:
# Alternatively use -  .isin():

mydf[mydf["City"].isin(["Chennai", "Bangalore", "Hyderabad", "Delhi"])]

In [ ]:
# Q14) Get all students who are not staying in "Bangalore" or "Hyderabad".

mydf[~mydf['City'].isin(['Bangalore', 'Hyderabad'])]

   studentId   Name  Age Course     City    Fee
1        102    Vas   30     ML  Chennai  25000
4        105     OK   45     DL    Delhi  22000
6        107  Hello   35     DL     Pune  17000
7        108    Vas   28     ML  Chennai  24000

In [ ]:
# Q15) Get all students whose Fee is between 18,000 and 24,000 (inclusive).

mydf[(mydf['Fee'] >= 18000) & (mydf['Fee'] <= 24000)]

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
5        106       Hai   30      ML  Hyderabad  21000
7        108       Vas   28      ML    Chennai  24000

In [ ]:
# Alternatively use -  .between():

mydf[mydf['Fee'].between(18000, 24000, inclusive="both")]

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
5        106       Hai   30      ML  Hyderabad  21000
7        108       Vas   28      ML    Chennai  24000

In [ ]:
# Q16) Get all students whose Age is between 25 and 35 (exclusive).

mydf[(mydf['Age'] > 25) & (mydf['Age'] < 35)]

   studentId Name  Age Course       City    Fee
1        102  Vas   30     ML    Chennai  25000
5        106  Hai   30     ML  Hyderabad  21000
7        108  Vas   28     ML    Chennai  24000

In [ ]:
# Alternatively using .between():

mydf[mydf['Age'].between(25, 35, inclusive="neither")]

   studentId Name  Age Course       City    Fee
1        102  Vas   30     ML    Chennai  25000
5        106  Hai   30     ML  Hyderabad  21000
7        108  Vas   28     ML    Chennai  24000

In [ ]:
# using .between():

mydf[mydf['Age'].between(25, 35, inclusive="left")]

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
5        106       Hai   30     ML  Hyderabad  21000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# using .between():

mydf[mydf['Age'].between(25, 35, inclusive="right")]

   studentId   Name  Age Course       City    Fee
1        102    Vas   30     ML    Chennai  25000
2        103  Hello   35     ML  Bangalore  15000
5        106    Hai   30     ML  Hyderabad  21000
6        107  Hello   35     DL       Pune  17000
7        108    Vas   28     ML    Chennai  24000

## **4) query() Method**

In [ ]:
# Q17) Get all students whose age is greater than 30.

mydf.query("Age > 30")

   studentId      Name  Age  Course       City    Fee
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
6        107     Hello   35      DL       Pune  17000

In [ ]:
# Q18) Get all students from Bangalore.

mydf.query("City == 'Bangalore'")

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000

In [ ]:
# Q19) Get all students whose fee is at least ₹20,000.

mydf.query("Fee >= 20000")

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
4        105        OK   45     DL      Delhi  22000
5        106       Hai   30     ML  Hyderabad  21000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q20) Get all students whose city is either 'Chennai' or 'Delhi'.

mydf.query("City in ['Chennai', 'Delhi']")

   studentId Name  Age Course     City    Fee
1        102  Vas   30     ML  Chennai  25000
4        105   OK   45     DL    Delhi  22000
7        108  Vas   28     ML  Chennai  24000

In [ ]:
# Q21) Get all students whose course is not 'Python'.

mydf.query("Course != 'Python'")

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
2        103     Hello   35     ML  Bangalore  15000
4        105        OK   45     DL      Delhi  22000
5        106       Hai   30     ML  Hyderabad  21000
6        107     Hello   35     DL       Pune  17000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q22) Get all students whose age is between 25 and 35 (inclusive).

mydf.query("Age >= 25 & Age <= 35")

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
2        103     Hello   35     ML  Bangalore  15000
5        106       Hai   30     ML  Hyderabad  21000
6        107     Hello   35     DL       Pune  17000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q23) Get all students whose age is less than 30 or fee is more than ₹23,000.

mydf.query("Age < 30 | Fee > 23000")

   studentId      Name  Age Course       City    Fee
0        101  Srinivas   25     ML  Bangalore  20000
1        102       Vas   30     ML    Chennai  25000
7        108       Vas   28     ML    Chennai  24000

In [ ]:
# Q24) Get all students whose name starts with 'S'.

mydf.query("Name.str.startswith('S')")

   studentId      Name  Age  Course       City    Fee
0        101  Srinivas   25      ML  Bangalore  20000
3        104  Srinivas   40  Python  Bangalore  18000

## **5) Filtering with loc[] (label-based)**

* loc[] selects rows and columns by labels (names), not by positions.

**Syntax:**

```
df.loc[row_labels, column_labels]
```

In [ ]:
# Q25) Get studentId, Name and City of student with studentId 105

mydf.loc[mydf['studentId'] == 105, ['studentId','Name', 'City']]

   studentId Name   City
4        105   OK  Delhi

In [ ]:
# Q26) Get Name, Age, 'City' and Fee of students from Bangalore

mydf.loc[mydf['City'] == 'Bangalore', ['Name', 'Age', 'Fee','City']]

       Name  Age    Fee       City
0  Srinivas   25  20000  Bangalore
2     Hello   35  15000  Bangalore
3  Srinivas   40  18000  Bangalore

In [ ]:
# Q27) Get all details of students whose Age > 35

mydf.loc[mydf['Age'] > 35, :]

   studentId      Name  Age  Course       City    Fee
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000

### **Querying the DataFrame**
* 3 ways to query the DataFrame
  * Querying the Dataframe with []
  * Querying the Dataframe with query() method
  * Querying the Dataframe loc() method

In [ ]:
# Querying the Dataframe with []
mydf[mydf['Age'] > 30]

In [ ]:
# Querying the Dataframe with query() method
mydf.query("Age > 30")

In [ ]:
# Querying the Dataframe loc() method
mydf.loc[mydf['Age'] > 30, :]

In [ ]:
mydf.iloc[2:6]

   studentId      Name  Age  Course       City    Fee
2        103     Hello   35      ML  Bangalore  15000
3        104  Srinivas   40  Python  Bangalore  18000
4        105        OK   45      DL      Delhi  22000
5        106       Hai   30      ML  Hyderabad  21000

In [ ]:
mydf.iloc[2:6,1:5]

       Name  Age  Course       City
2     Hello   35      ML  Bangalore
3  Srinivas   40  Python  Bangalore
4        OK   45      DL      Delhi
5       Hai   30      ML  Hyderabad

In [ ]:
mydf.loc[2:6,'Name':'City']

       Name  Age  Course       City
2     Hello   35      ML  Bangalore
3  Srinivas   40  Python  Bangalore
4        OK   45      DL      Delhi
5       Hai   30      ML  Hyderabad
6     Hello   35      DL       Pune

# **Module 4: Data Cleaning and Preprocessing**
  * Handling Missing Data
  * Type Conversion
  * String Operations
  * Duplicates Handling
  * Mapping and Replacing Values

In [ ]:
import pandas as pd

mydf = pd.read_csv("mystudents_data_1.csv")

mydf

    studentId          Name       Age     Course        City    Fee   Marks
0         101    srinivas          25         ML   Bangalore    20k      85
1         102           Vas        30     DevOps     Chennai  25000      90
2         103         Hello       NaN       Java   Bangalore  15000     NaN
3         104        Manish        40     Python      Mumbai  18000     78%
4         105          Amit        45         DL         NaN  22000    88.5
5         106           Hai        30         ML   hyderabad  21000      72
6         107         Hello        35         DL        Pune  17000   sixty
7         108           Vas        28        ai      Chennai  24000      95
8         109           RAJ        32         ML      Mumbai  19000  65/100
9         110            Ok        26        NaN       Delhi  16000      68
10        111          Alok  38 years     Python  BANGALORE   23000    88,5
11        112         Super        29  Dev   Ops        Pune    NaN     NaN
12        104        Manish        40     Python      Mumbai  18000     78%
13        108           Vas        28         AI     Chennai  24500      96
14        113          Siri        27         ML   Bangalore  20000     NaN
15        114         Kiran       NaN        NaN         NaN    NaN  absent
16        101    srinivas          25         ML   Bangalore    20k      85
17        109           RAJ        32         ML      Mumbai  19000  65/100
18        115         Hello        35         DL        Pune  17100   sixty
19        108           Vas        28        AI      Chennai  25000      92
20        201           NaN       NaN        NaN         NaN    NaN     NaN
21        202           NaN       NaN        NaN         NaN    NaN     NaN

# **A) Handling Missing Data**

## **1) Converting placeholders to real NaN**

* a) replace(..., value=pd.NA)

**a) replace(..., value=pd.NA)**
* Turn “fake” missing markers into true NaN so you can fill/drop consistently.

In [ ]:
import numpy as np

print(mydf['Marks'].isna().sum()) #3

placeholders = {'na', 'n/a', 'none', 'null', 'missing', 'absent', 'nan', ''}

mask = mydf['Marks'].astype(str).str.strip().str.lower().isin(placeholders)
mydf.loc[mask, 'Marks'] = np.nan;

print(mydf['Marks'].isna().sum()) #4

5
6

In [ ]:
placeholders = {'na', 'n/a', 'none', 'null', 'missing', 'absent', 'nan', ''}

for mycol in mydf.select_dtypes(include=['object', 'string', 'integer', 'floating']).columns:
    print(mydf[mycol].isna().sum())
    mask = mydf[mycol].astype('string').str.strip().str.lower().isin(placeholders)
    mydf.loc[mask, mycol] = np.nan
    print(mydf[mycol].isna().sum())

0
0
2
2
4
4
4
4
4
4
4
4
6
6

In [ ]:
mydf

    studentId          Name       Age     Course        City    Fee   Marks
0       101.0    srinivas          25         ML   Bangalore    20k      85
1       102.0           Vas        30     DevOps     Chennai  25000      90
2       103.0         Hello       NaN       Java   Bangalore  15000     NaN
3       104.0        Manish        40     Python      Mumbai  18000     78%
4       105.0          Amit        45         DL         NaN  22000    88.5
5       106.0           Hai        30         ML   hyderabad  21000      72
6       107.0         Hello        35         DL        Pune  17000   sixty
7       108.0           Vas        28        ai      Chennai  24000      95
8       109.0           RAJ        32         ML      Mumbai  19000  65/100
9       110.0            Ok        26        NaN       Delhi  16000      68
10      111.0          Alok  38 years     Python  BANGALORE   23000    88,5
11      112.0         Super        29  Dev   Ops        Pune    NaN     NaN
12      104.0        Manish        40     Python      Mumbai  18000     78%
13      108.0           Vas        28         AI     Chennai  24500      96
14      113.0          Siri        27         ML   Bangalore  20000     NaN
15      114.0         Kiran       NaN        NaN         NaN    NaN     NaN
16      101.0    srinivas          25         ML   Bangalore    20k      85
17      109.0           RAJ        32         ML      Mumbai  19000  65/100
18      115.0         Hello        35         DL        Pune  17100   sixty
19      108.0           Vas        28        AI      Chennai  25000      92
20      201.0           NaN       NaN        NaN         NaN    NaN     NaN
21      202.0           NaN       NaN        NaN         NaN    NaN     NaN

## **2) Convert unparseable values to NaN**

* a) to_numeric(..., errors='coerce')

**a) to_numeric(..., errors='coerce')**
* When numbers are stored as  text—failed parses become NaN (then fill/drop).

In [ ]:
mydf

In [ ]:
mydf['Age'] = pd.to_numeric(mydf['Age'], errors='coerce')   # '38 years' -> NaN, '30 ' -> 30

mydf['Fee'] = pd.to_numeric(mydf['Fee'], errors='coerce')   # '17000' -> 17000, '20k' -> NaN

mydf['Marks'] = pd.to_numeric(mydf['Marks'], errors='coerce') # '85' → 85, '78%', '65/100', '88,5', 'sixty'-> NaN

In [ ]:
mydf

    studentId          Name   Age     Course        City      Fee  Marks
0       101.0    srinivas    25.0         ML   Bangalore      NaN   85.0
1       102.0           Vas  30.0     DevOps     Chennai  25000.0   90.0
2       103.0         Hello   NaN       Java   Bangalore  15000.0    NaN
3       104.0        Manish  40.0     Python      Mumbai  18000.0    NaN
4       105.0          Amit  45.0         DL         NaN  22000.0   88.5
5       106.0           Hai  30.0         ML   hyderabad  21000.0   72.0
6       107.0         Hello  35.0         DL        Pune  17000.0    NaN
7       108.0           Vas  28.0        ai      Chennai  24000.0   95.0
8       109.0           RAJ  32.0         ML      Mumbai  19000.0    NaN
9       110.0            Ok  26.0        NaN       Delhi  16000.0   68.0
10      111.0          Alok   NaN     Python  BANGALORE   23000.0    NaN
11      112.0         Super  29.0  Dev   Ops        Pune      NaN    NaN
12      104.0        Manish  40.0     Python      Mumbai  18000.0    NaN
13      108.0           Vas  28.0         AI     Chennai  24500.0   96.0
14      113.0          Siri  27.0         ML   Bangalore  20000.0    NaN
15      114.0         Kiran   NaN        NaN         NaN      NaN    NaN
16      101.0    srinivas    25.0         ML   Bangalore      NaN   85.0
17      109.0           RAJ  32.0         ML      Mumbai  19000.0    NaN
18      115.0         Hello  35.0         DL        Pune  17100.0    NaN
19      108.0           Vas  28.0        AI      Chennai  25000.0   92.0
20      201.0           NaN   NaN        NaN         NaN      NaN    NaN
21      202.0           NaN   NaN        NaN         NaN      NaN    NaN

## **3) Detecting missing values**

* a) isnull() / isna()
* b) notnull() / notna()
* c) Row-wise checks with any() / all()
* d) Check Null percentages

**a) isnull() / isna()**

* Find missing values (returns True/False).
* They both treat NaN, None, and NaT as missing.
* literal string like "NaN" is not missing.

In [ ]:
# nulls per column
mydf.isnull()

In [ ]:
# nulls per column
mydf.isnull().sum()

In [ ]:
# nulls per column
mydf.isna().sum()

In [ ]:
mydf['Course'].isna().sum()

np.int64(2)

In [ ]:
mydf['Marks'].isna().sum()

np.int64(11)

In [ ]:
# Rows where Course is null
mydf[mydf['Course'].isna() ]

In [ ]:
# Rows where Age is null
mydf[ mydf['Age'].isna() ]

In [ ]:
# Rows where Marks is null
mydf[ mydf['Marks'].isna() ]

**b) notnull() / notna()**
* Find non-missing values (returns True/False).

In [ ]:
mydf['City'].notna()

In [ ]:
# Rows where City is present
mydf[ mydf['City'].notna() ]

In [ ]:
mydf['Marks'].notnull()

In [ ]:
# Rows where Marks is present
mydf[ mydf['Marks'].notnull() ]

**c) Row-wise checks with any() / all()**
* Flag rows with any/all nulls.
* **mydf.isnull()** → a DataFrame of booleans (True where the cell is missing; False otherwise).
* **.any(axis=1)** → for each row, checks if any column is True (i.e., at least one missing in that row).
* **.all(axis=1)** → for each row, checks if all columns are True (i.e., the row is entirely missing).

In [ ]:
# Display the Row if any column is missing
mydf[ mydf.isna().any(axis=1) ]

In [ ]:
# Display the Row if All the Columns are missing
mydf[ mydf.isna().all(axis=1) ]

Empty DataFrame
Columns: [studentId, Name, Age, Course, City, Fee, Marks]
Index: []

In [ ]:
# Count the Row if any column is missing
num_any = mydf.isna().any(axis=1).sum()

print(num_any)

15

In [ ]:
# Count the Row if all columns are missing
num_all = mydf.isnull().all(axis=1).sum()

print(num_all)

0

**d) Null percentages**
* How much of each column is missing (in %).

In [ ]:
mydf.isna().mean() * 100

studentId     0.0
Name          0.0
Age          15.0
Course       10.0
City         10.0
Fee          20.0
Marks        55.0
dtype: float64

In [ ]:
(mydf.isna().mean() * 100).sort_values(ascending=False)

Marks        55.0
Fee          20.0
Age          15.0
City         10.0
Course       10.0
Name          0.0
studentId     0.0
dtype: float64

## **4) Filling missing values**

* a) fillna(value)
* b) fillna(method='ffill' | 'bfill', limit=...) - Deprecated
* c) ffill()
* d) bfill()

**a) fillna(value)**
* Fill nulls with a constant or computed value.

In [ ]:
mydf

In [ ]:
mydf['Course'] = mydf['Course'].fillna('Deep Learning')

mydf['Course']

In [ ]:

mydf['Fee'] = mydf['Fee'].fillna(mydf['Fee'].median())

mydf['Fee']

In [ ]:
mydf['Age'] = mydf['Age'].fillna(mydf['Age'].median())

mydf['Age']

**b) ffill(limit=1)**
* Forward fill from neighbors (good for time-like data).

In [ ]:
# check Null Count
null_count = mydf['Age'].isna().sum()
print(null_count)

# Forward-fill only the first NaN in each block
mydf['Age'] = mydf['Age'].ffill(limit=1)

# check Null Count
null_count = mydf['Age'].isna().sum()
print(null_count)

0
0

**c) bfill(limit=1)**
* Backward fill from the next non-null value (good for time-like data).

In [ ]:
# check Null Count
null_count = mydf['Fee'].isna().sum()
print(null_count)

# Backward-fill only the first NaN in each block
mydf['Fee'] = mydf['Fee'].bfill(limit=1)

# check Null Count
null_count = mydf['Fee'].isna().sum()
print(null_count)

0
0

In [ ]:
myseries = pd.Series([10,np.nan,np.nan,40,np.nan,50])
print(myseries)

#myseries = myseries.ffill(limit=1)
#print(myseries)

#myseries = myseries.bfill(limit=1)
#print(myseries)

#myseries = myseries.ffill()
#print(myseries)

myseries = myseries.bfill()
print(myseries)

## **5) Interpolating numeric gaps**

* a) interpolate(method=...)

**a) interpolate(method=...)**
* Estimate numeric nulls from nearby values.

In [ ]:
mydf['Age'] = mydf['Age'].interpolate(method='linear')

In [ ]:
# mydf['Age'] = mydf['Age'].interpolate(method='linear')
# mydf['Age'] = mydf['Age'].interpolate(method='linear', limit=1)
# mydf['Age'] = mydf['Age'].interpolate(method='nearest')

# mydf['Age'] = mydf['Age'].interpolate(method='pad')   # or method='ffill'
# mydf['Age'] = mydf['Age'].interpolate(method='backfill')  # or method='bfill'

In [ ]:
import numpy as np
import pandas as pd

myseries = pd.Series([10,np.nan,np.nan,40,np.nan,50])

myseries = myseries.interpolate(method="linear")
print(myseries)

#myseries = myseries.interpolate(method="linear",limit=1)
#print(myseries)

#myseries = myseries.interpolate(method="nearest")
#print(myseries)

#myseries = myseries.interpolate(method="pad") # deprecated ( use ffill)
#print(myseries)

#myseries = myseries.interpolate(method="backfill") # deprecated ( use bfill)
#print(myseries)

0    10.0
1    20.0
2    30.0
3    40.0
4    45.0
5    50.0
dtype: float64

## **6) Dropping missing values**

* a) dropna(subset=..., how=..., thresh=..., axis=...)

**a) dropna(subset=..., how=..., thresh=..., axis=...)**
* Remove rows/columns with missing values by rule.
* **axis:** 0 = rows (default), 1 = columns
* **subset:** only look at these columns when deciding to drop rows
* **how:** 'any' (drop if any NA) or 'all' (drop if all NA)
* **thresh:** minimum number of non-NA values required to keep the row/column

In [ ]:
mydf

In [ ]:
 # keep rows where Marks is present
 # Drop the Rows where Marks are NaN
mydf_rows = mydf.dropna(subset=['Marks'])

mydf_rows

In [ ]:
# drop rows where all columns are NaN
mydf_rows = mydf.dropna(how='all')

mydf_rows

In [ ]:
# keep rows only if BOTH Fee and Marks are present
mydf.dropna(subset=['Fee','Marks'], how='any')

In [ ]:
# keep rows unless BOTH Fee and Marks are missing
mydf.dropna(subset=['Fee','Marks'], how='all')

In [ ]:
(mydf.isna().mean()*100).round(2).sort_values(ascending=False)

Marks        59.09
Fee          27.27
Age          22.73
City         18.18
Course       18.18
Name          9.09
studentId     0.00
dtype: float64

In [ ]:
# drop columns with >=50% missing (keep <50% filled)
mydf.dropna(axis=1, thresh=int(0.5*len(mydf)))

In [ ]:
# drop columns with >=20% missing (keep <90% filled)
mydf.dropna(axis=1, thresh=int(0.85*len(mydf)))

In [ ]:
mydf

In [ ]:
# drop rows that have fewer than 3 non-NA values (across all columns)
mydf.dropna(axis=0, thresh=3,inplace=True)

mydf

In [ ]:
# drop rows that have fewer than 3 non-NA values (across all columns)
mydf.dropna(axis=1, thresh=int(0.42*len(mydf)),inplace=True)

mydf

# **B) Type Conversion**
* a) pd.to_numeric(..., errors='coerce', downcast=...)
* b) astype(...)
* c) pd.to_datetime(..., errors='coerce')
* d) Downcasting for memory
* e) convert_dtypes()

In [ ]:
import pandas as pd

mydf = pd.read_csv("mystudents_data_1.csv")

mydf

**a) pd.to_numeric(..., errors='coerce', downcast=...)**
* Safely parse messy numbers; bad parses → NaN (then you can fill/drop).

In [ ]:
mydf.dtypes

In [ ]:

mydf['Age'] = pd.to_numeric(mydf['Age'], errors='coerce')
mydf['Fee'] = pd.to_numeric(mydf['Fee'], errors='coerce')
mydf['Marks'] = pd.to_numeric(mydf['Marks'], errors='coerce')

mydf.dtypes

studentId      int64
Name          object
Age          float64
Course        object
City          object
Fee          float64
Marks        float64
dtype: object

**b) astype(...)**
* Explicitly cast to a target dtype (use nullable types if NaNs exist).

In [ ]:
# numerics
mydf['Age']   = mydf['Age'].astype('Int64')
mydf['Fee']   = mydf['Fee'].astype('Int64')
mydf['Marks'] = mydf['Marks'].astype('Float64')

# strings
mydf['Name'] = mydf['Name'].astype('string')
mydf['City'] = mydf['City'].astype('string')
mydf['Course'] = mydf['Course'].astype('string')

# mydf[['Name','City','Course']] = mydf[['Name','City','Course']].astype('string')

# boolean
# mydf['HasFee'] = mydf['Fee'].notna().astype('boolean')

mydf['HasFee'] = mydf['Fee'].notna()
mydf['HasFee'] = mydf['HasFee'].astype('boolean')

mydf.dtypes

studentId             int64
Name         string[python]
Age                   Int64
Course       string[python]
City         string[python]
Fee                   Int64
Marks               Float64
HasFee              boolean
dtype: object

In [ ]:
mydf

**c) pd.to_datetime(..., errors='coerce')**
* Parse date strings to datetime (coerce unparseable to NaT).

In [ ]:
#mydf['Age'] = pd.to_numeric(mydf['Age'], errors='coerce')

# mydf['JoinDate'] = pd.to_datetime(mydf['JoinDate'], errors='coerce')

**d) convert_dtypes()**
* Auto-infer better dtypes (nullable Int64/Float64, string, boolean).

In [ ]:
import pandas as pd

mydf = pd.read_csv("mystudents_data_1.csv")

mydf.dtypes

studentId     int64
Name         object
Age          object
Course       object
City         object
Fee          object
Marks        object
dtype: object

In [ ]:
mydf = mydf.convert_dtypes()

mydf.dtypes

studentId             Int64
Name         string[python]
Age                   Int64
Course       string[python]
City         string[python]
Fee                   Int64
Marks               Float64
HasFee              boolean
dtype: object

# **C) String Operations**
* a) str.strip(), str.lstrip(), str.rstrip()
* b) str.contains(substring, case=False, na=False)
* c) str.startswith() / str.endswith()
* d) str.replace(old, new) (literal substring)
* e) str.split(..., expand=True)

In [ ]:
mydf.dtypes

studentId             Int64
Name         string[python]
Age                   Int64
Course       string[python]
City         string[python]
Fee                   Int64
Marks               Float64
HasFee              boolean
dtype: object

**a) Trim & Case - str.strip(), str.lstrip(), str.rstrip()**
* Remove spaces at both/left/right ends.

In [ ]:
mydf

    studentId          Name   Age     Course        City    Fee  Marks  HasFee
0         101    srinivas      25         ML   Bangalore   <NA>   85.0   False
1         102           Vas    30     DevOps     Chennai  25000   90.0    True
2         103         Hello  <NA>       Java   Bangalore  15000   <NA>    True
3         104        Manish    40     Python      Mumbai  18000   <NA>    True
4         105          Amit    45         DL        <NA>  22000   88.5    True
5         106           Hai    30         ML   hyderabad  21000   72.0    True
6         107         Hello    35         DL        Pune  17000   <NA>    True
7         108           Vas    28        ai      Chennai  24000   95.0    True
8         109           RAJ    32         ML      Mumbai  19000   <NA>    True
9         110            Ok    26       <NA>       Delhi  16000   68.0    True
10        111          Alok  <NA>     Python  BANGALORE   23000   <NA>    True
11        112         Super    29  Dev   Ops        Pune   <NA>   <NA>   False
12        104        Manish    40     Python      Mumbai  18000   <NA>    True
13        108           Vas    28         AI     Chennai  24500   96.0    True
14        113          Siri    27         ML   Bangalore  20000   <NA>    True
15        114         Kiran  <NA>       <NA>        <NA>   <NA>   <NA>   False
16        101    srinivas      25         ML   Bangalore   <NA>   85.0   False
17        109           RAJ    32         ML      Mumbai  19000   <NA>    True
18        115         Hello    35         DL        Pune  17100   <NA>    True
19        108           Vas    28        AI      Chennai  25000   92.0    True
20        201          <NA>  <NA>       <NA>        <NA>   <NA>   <NA>   False
21        202          <NA>  <NA>       <NA>        <NA>   <NA>   <NA>   False

In [ ]:
# Trim the Spaces and Make it to Title Ccase or Upper Case
mydf['City']   = mydf['City'].str.strip().str.title()   # 'BANGALORE ' → 'Bangalore'
mydf['Course'] = mydf['Course'].str.strip().str.upper() # ' ai ' → 'AI'
mydf['Name']   = mydf['Name'].str.strip().str.title()   # '  srinivas  ' → 'Srinivas'

mydf[['Name','Course','City']]

**b) Find / Filter**
**str.contains(substring, case=False, na=False)**
* Filter rows where substring appears (case-insensitive).

**str.startswith() / str.endswith()**
* Filter by prefix/suffix.

In [ ]:
mydf['Name'].str.contains('as', case=False, na=False)

In [ ]:
mydf[ mydf['Name'].str.contains('as', case=False, na=False) ]

    studentId      Name  Age  Course       City    Fee  Marks  HasFee
0         101  Srinivas   25      ML  Bangalore   <NA>   85.0   False
1         102       Vas   30  DEVOPS    Chennai  25000   90.0    True
7         108       Vas   28      AI    Chennai  24000   95.0    True
13        108       Vas   28      AI    Chennai  24500   96.0    True
16        101  Srinivas   25      ML  Bangalore   <NA>   85.0   False
19        108       Vas   28      AI    Chennai  25000   92.0    True

In [ ]:
mydf[ mydf['Name'].str.startswith('S', na=False) ]

    studentId      Name  Age     Course       City    Fee  Marks  HasFee
0         101  Srinivas   25         ML  Bangalore   <NA>   85.0   False
11        112     Super   29  DEV   OPS       Pune   <NA>   <NA>   False
14        113      Siri   27         ML  Bangalore  20000   <NA>    True
16        101  Srinivas   25         ML  Bangalore   <NA>   85.0   False

In [ ]:
mydf[ mydf['Course'].str.endswith('N', na=False) ]

**c) Replace - str.replace(old, new) (literal substring)**
* Fix common variants and typos.

In [ ]:
mydf['City'] = mydf['City'].str.strip().str.replace('Bengaluru', 'Bangalore')
mydf['Course'] = mydf['Course'].str.strip().str.replace('DEV   OPS', 'DEVOPS')

mydf[['Name','Course','City']]

In [ ]:

mydf['City'] = (mydf['City'].str.lower()
                             .str.replace('bangaluru', 'bangalore')
                             .str.title())

**d) Split / Join - str.split(..., expand=True)**
* Split into multiple columns.

In [ ]:
parts = mydf['Name'].astype('string').str.strip().str.split(n=1)  # Series of lists

mydf['FirstName'] = parts.str[0]   # always present
mydf['Rest']      = parts.str[1]   # becomes NaN when there was no second part

mydf

In [ ]:
# Collapse multiple spaces to one via split→join.
mydf['Name'] = mydf['Name'].str.split().str.join(' ')

# **D) Duplicates Handling**
* a) Count duplicates: value_counts()
* b) Exact duplicates - duplicated()
* c) Remove Duplicate keys

In [ ]:
import pandas as pd

mydf = pd.read_csv("mystudents_data_1.csv")
mydf

**a) Count duplicates: value_counts()**
* Use value_counts() to see how many times each key or pair appears.

In [ ]:
# counts per studentId
mydf['studentId'].value_counts()

In [ ]:
# counts per City
mydf.value_counts(subset=['City'])

In [ ]:
# counts per (Name, City) pair
mydf.value_counts(subset=['Name','City'])

**b) Exact duplicates - duplicated()**
* Detect the rows that are identical across every column.

In [ ]:
dup_count = mydf.duplicated().sum()
print(dup_count)

mydf[ mydf.duplicated(keep=False) ]

In [ ]:
dup_count = mydf.duplicated(subset=['studentId'], keep=False).sum()
print(dup_count)

mydf[ mydf.duplicated(subset=['studentId'], keep=False) ]

**c) Remove Duplicate keys**
* drop_duplicates(subset=...).
* Find multiple rows sharing the key and keep the desired one

In [ ]:
mydf = mydf.drop_duplicates(keep='first')

dup_count = mydf.duplicated().sum()
print(dup_count)

mydf

In [ ]:
mydf = mydf.drop_duplicates(subset=['studentId'], keep='last')

dup_count = mydf.duplicated(subset=['studentId'], keep=False).sum()
print(dup_count)

mydf

# **E) Mapping and Replacing Values**
* a) map(dict)
* b) map(dict)
* c) replace(old→new)
* d) DataFrame.replace({...})
* e) cut()
* f) apply(func)

In [ ]:
import pandas as pd

mydf = pd.read_csv("mystudents_data_1.csv")

mydf

**a) map(dict)**
* Best for one-column lookups;
* Unmapped → NaN (so often followed by fillna).

In [ ]:
city2code = {'Bangalore':'BLR','Hyderabad':'HYD','Chennai':'CNA','Mumbai':'MUM','Delhi':'DEL','Pune':'PUN'}

mydf['City'] = mydf['City'].map(city2code).fillna(np.nan)

mydf

**b) map(dict)**
* Keep original when no mapping exists

In [ ]:
course_fix = {'DEV   OPS':'DEVOPS','ai':'AI','PY':'PYTHON'}

mydf['Course'] = mydf['Course'].map(course_fix).fillna(mydf['Course'])

mydf['Course']

**c) replace(old→new)**
* Change only the matched values; others untouched.

In [ ]:
mydf['Name'] = mydf['Name'].replace({'Ok':'Okay','Hai':'Hi'})

mydf['Name']

**d) DataFrame.replace({...})**
* Multi-column replace
* One call to fix multiple columns.

In [ ]:
mydf = mydf.replace({
    'City':   {'Bengaluru':'Bangalore', 'Hyd':'Hyderabad'},
    'Course': {'Dev Ops':'DEVOPS', 'Js':'JAVA'}
})

mydf.head()

**e) cut()**
* Bins continuous values into labeled intervals and returns an ordered categorical series.

In [ ]:
mydf = mydf.copy()
mydf['Marks_num'] = pd.to_numeric(mydf['Marks'], errors='coerce')

mybins   = [0, 70, 80, 90, 100]             # 0–70, 70–80, 80–90, 90–100
mylabels = ['D','C','B','A']

mydf['Grade1'] = pd.cut(mydf['Marks_num'], bins=mybins, labels=mylabels,right=False)

mydf[["Name","Marks_num","Grade1"]]

**f) apply(func)**
* Runs a custom Python function over a Series (element-wise) or a DataFrame (row/column-wise)

In [ ]:
def find_grade(marks):
    if pd.isna(marks): return pd.NA
    if marks >= 90: return 'A'
    if marks >= 80: return 'B'
    if marks >= 70: return 'C'
    return 'D'

mydf['Grade2'] = mydf['Marks_num'].apply(find_grade)

mydf[["Name", 'Marks_num','Grade1','Grade2']].head()

In [ ]:
def make_label(row):
    # be robust to missing values and mixed cases
    name  = str(row['Name']).strip().title()  if pd.notna(row['Name'])  else 'Unknown'
    course= str(row['Course']).strip().upper() if pd.notna(row['Course']) else 'UNKNOWN'
    city  = str(row['City']).strip().upper()  if pd.notna(row['City'])  else 'NA'
    return f"{name} | {course} @ {city}"

# Row-wise apply because we use multiple columns
mydf['Label'] = mydf.apply(make_label, axis=1)

mydf[['Name','Course','City','Label']].head()

In [ ]:
mydf[mydf["Marks_num"].notna()][['Name','Marks_num']]

In [ ]:

mydf["Marks_Updated"] = mydf["Marks_num"].apply(lambda x: x+10 if x<90 else x)

In [ ]:
mydf[mydf["Marks_num"].notna()][['Name','Marks_num','Marks_Updated']]